#!/bin/bash 
# specify the QP folder 
# script that copy all data in ao_extra_basis and extra_nuclei and copy it to ao_basis and ao_nuclei
QP=$QP_ROOT
dir=${QP}
# sourcing the quantum_package.rc file
. ${QP}/quantum_package.rc
EZFIO_extra=${1%/}
EZFIO_target=${2%/}



echo "********** SCRIPT TO COPY DATA FROM EZFIO TO ANOTHER *********"
echo "Extracting data from "$EZFIO_extra 
echo "and Copying data to  "$EZFIO_target

### COPYING ALL DATA FROM $EZFIO_extra/nuclei/ to ${EZFIO_target}/extra_nuclei/
echo "COPYING ALL DATA FROM "$EZFIO_extra"/extra_nuclei/ to "${EZFIO_target}"/nuclei/"
direxists=false
if [ -d ${EZFIO_target}/extra_nuclei/ ] ; then
 direxists=true
 echo "The directory extra_nuclei exists"
 else
 echo "PB !!"
 direxists=false
 mkdir ${EZFIO_target}/extra_nuclei/
fi
data=`\ls $EZFIO_extra/extra_nuclei/`
for i in $data
do
 echo $i
 newfile=`echo $i | sed 's/extra_nucl/nucl/g' `
 echo $newfile
 cp ${EZFIO_extra}/extra_nuclei/$i ${EZFIO_target}/nuclei/$newfile
done

### COPYING ALL DATA FROM $EZFIO_extra/ao_basis/ to ${EZFIO_target}/ao_extra_basis/
direxists=false
if [ -d ${EZFIO_target}/ao_extra_basis/ ] ; then
 direxists=true
 echo "The directory exists ao_extra_basis"
 else
 echo "PB !!"
 direxists=false
 mkdir ${EZFIO_target}/ao_extra_basis/
fi
echo "COPYING ALL DATA FROM "$EZFIO_extra"/ao_basis/ to "${EZFIO_target}"/ao_extra_basis/"
data=`\ls $EZFIO_extra/ao_extra_basis/`
for i in $data
do
 echo $i
 newfile=`echo $i | sed 's/ao_extra/ao/g' `
 echo $newfile
 cp ${EZFIO_extra}/ao_extra_basis/$i ${EZFIO_target}/ao_basis/$newfile
done


