#!/bin/bash 
## Takes as an argument an xyz file and a basis, and fit the AO basis onto an "s" basis only
## use: 
# qp_fit_1s_basis my_xyz_file.xyz basis
source ~/qp2/quantum_package.rc
input=${1%.xyz}
basis=$2
ezfio_fit=${input}_${basis}_1s
qp create_ezfio -b $basis $input.xyz -o $ezfio_fit
# Fitting the original basis on 1s only basis functions
qp run fit_1s_basis |tee ${ezfio_fit}.fit_1s.out
qp_copy_extra_basis_to_usual_basis $ezfio_fit $ezfio_fit
