os: linux
dist: bionic
compiler: gfortran

env:
  - OPAMROOT=$HOME/.opam

cache:
  directories:
  - $HOME/.opam/

language: python
python:
    - "2.7"

jobs:
  include:
  - name: default gcc 
    addons:
      apt:
        packages:
          - gfortran
          - gcc
          - liblapack-dev
          - libblas-dev
          - wget
    script: 
      - ./configure --install all --config ./config/travis.cfg 
      - source ./quantum_package.rc ; ninja -j 1 -v 
      - source ./quantum_package.rc ; qp_test -a 

  - name: default gcc 9 
    addons:
      apt:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
          key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f    
        packages:
          - gfortran-9
          - gcc-9
          - liblapack-dev
          - libblas-dev
          - wget
    script: 
      - ./configure --install all --config ./config/travis.cfg 
      - source ./quantum_package.rc ; ninja -j 1 -v 
      - source ./quantum_package.rc ; qp_test -a 
