os: linux
dist: bionic

env:
  - OPAMROOT=$HOME/.opam

cache:
  directories:
  - $HOME/.opam/

language: python
python:
    - "2.7"

jobs:
  include:
  - name: default-gcc
    addons:
      apt:
        packages:
        - gfortran
        - gcc
        - liblapack-dev
        - libblas-dev
        - wget
    compiler: gfortran
    script: 
      - ./configure --install all --config ./config/travis.cfg 
      - source ./quantum_package.rc ; ninja -j 1 -v 
      - source ./quantum_package.rc ; qp_test -a 
  - name: gcc-9
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
          key_url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x60c317803a41ba51845e371a1e9377a2ba9ef27f    
        packages:
        - gfortran-9
        - gcc-9
        - liblapack-dev
        - libblas-dev
        - wget
    compiler: gfortran
    script: 
      - ./configure --install all --config ./config/travis.cfg 
      - source ./quantum_package.rc ; ninja -j 1 -v 
      - source ./quantum_package.rc ; qp_test -a 
  - name: intel
    env: 
      - CXX='icpc'
      - FC='ifort'
      - CXX='icc'
    install:
    - source /opt/intel/inteloneapi/compiler/latest/env/vars.sh
    addons:
      apt:
        sources:
        - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
          key_url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        packages:
        - intel-oneapi-icc
        - intel-oneapi-ifort
        - liblapack-dev
        - libblas-dev
        - wget
    compiler: ifort
    script: 
      - ./configure --install all --config ./config/ifort_debug.cfg 
      - source ./quantum_package.rc ; ninja -j 1 -v 
      - source ./quantum_package.rc ; qp_test -a 
