name: QP CI

on:
  push:
    branches:
    - master
    - dev-stable
  pull_request:
    branches: 
    - dev-stable
    - master
  schedule:
  - cron: "23 22 * * 6"
  workflow_dispatch:

      
jobs:

  configuration:
    runs-on: ubuntu-20.04
    name: Dependencies

    steps:
       - uses: actions/checkout@v2
       - name: install dependencies
         run: |
           sudo apt install gfortran gcc liblapack-dev libblas-dev wget python3 make m4 pkg-config
    
  compilation:
    name: Compilation
    runs-on: ubuntu-20.04
    needs: configuration
    
    steps:
       - uses: actions/checkout@v2
       - name: configure
         run: |
              ./configure -i all -c ./config/gfortran_debug.cfg
       - name: compile
         run: |
              bash -c "source quantum_package.rc ; exec ninja"



