name: QP CI

on:
  push:
    branches:
      - master
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches: [ dev-stable, master ]

jobs:

#  configuration:
#    runs-on: ubuntu-20.04
#    name: x86 Ubuntu 20.04
#
#    steps:
#       - uses: actions/checkout@v2
#       - name: install dependencies
#         run: |
#           sudo apt install gfortran gcc liblapack-dev libblas-dev wget python3 make m4 pkg-config
#
#
  compilation:
    runs-on: scemama666/qp2_env
    name: Compilation
    steps:
       - uses: actions/checkout@v2
       - name: configure
         run: |
              ./configure -i all -c ./config/gfortran_debug.cfg
       - name: compile
         run: |
              bash -c "source quantum_package.rc ; exec ninja"



